### ISSUE TITLE
Firewall Rules

### ISSUE THREAD

**Issue by sirmbhe** [BotoX/ServerStatus#9]
Hello,

I have been using your script for very long time, and now i have an issue. I am using a control panel called vestaCP and it add iptable/firewall on the installation package. But, it seems that it block the port that your script use for the connection to the main server. I already try to add rules, but it seems not working at all.

Any idea on how to solve the issue?

Many thanks,
Dhavid

**Comment by BotoX** [comment]
On the server running the "sergate" Daemon, aka. where your status website is hosted at you have to allow port 35601 TCP.
I don't use any control panels but with iptables you'd do it like this:
iptables -A INPUT -p tcp --dport 35601 -j ACCEPT


OH LOL, I just realized that in the readme it says "port 35061 TCP" but it should be 35601. Yep, it's probably because of this that it isn't working for you, oops!

**Comment by sirmbhe** [comment]
Haha, nope, i try to use the correct one and it still not working. Not sure where the problem is, right now the only way I could make it work are by stopping the iptable / firewall. If I try to start the firewall again, the serverstatus stopped again.

:(

**Comment by BotoX** [comment]
could you post the output of sudo iptables -L INPUT -n, it should include the changes you have made.

You should find something like this in there:
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:35601

If not then the rule isn't added.
